---
title: Game package 1 (10%)
---

You need to work in allocated groups to write an R package to help score or simulate a multi-player game. For example:

* **Blackjack**: Calculate the score from a round where the inputs are the cards held by the player and the dealer at the end of the game.
* **Poker**: Calculate the winner from a game where the inputs are the cards held by each player at the end of the game. Start with a simple version of poker, and extend to more complex versions.
* **500**: Score a game of 500 where the inputs are the cards played by each player for each trick.
* **Chess**: Simulate a game of chess with random but correct moves by each player.
* **Uno**: Simulate a game of uno with random draws.

You may also have your own ideas for a game. If you would like to do something else, please discuss it with Mitch and Rob first.

The package should have at least 3 user-facing functions, and a vignette that describes how to use the package. The package should be well-documented, with all user-facing functions having examples and unit tests.

Marks will be awarded for clean and efficient code, and for good design.

Please use the team names [allocated on Ed](https://edstem.org/au/courses/21222/discussion/2648997). If you are the first person on your team to accept the assignment, you will need to create the team. Otherwise, you should be able to join the team.


> **AI & Generative AI tools** may be used in *guided* ways within this assessment. If you used AI in completing this assignment, please explain how it was used, including any prompts. Where used, AI must be used responsibly, clearly documented and appropriately acknowledged (see [Learn HQ](https://www.monash.edu/student-academic-success/build-digital-capabilities/create-online/acknowledging-the-use-of-generative-artificial-intelligence)). Any work submitted for a mark must:
>
>  1. represent a sincere demonstration of your human efforts, skills and subject knowledge that you will be accountable for.
>  2. adhere to the guidelines for AI use set for the assessment task.
>  3. reflect the University’s commitment to academic integrity and ethical behaviour.
>
> Inappropriate AI use and/or AI use without acknowledgement will be considered a breach of academic integrity.

```{r}
#| output: asis
source(here::here("course_info.R"))
submit(schedule, "Game package 1")
```
